import streamlit as st
from typing import Tuple, Optional
from .auth import ensure_user_spotify  # spotipy client

def push_session_playlist(playlist_name: str = "Music4all – Session",
                          public: bool = False,
                          description: str = "Generated by Music4all (Spotify page)"
                          ) -> Tuple[Optional[str], int, int]:
    playlists = st.session_state.get("playlists", {})
    current = st.session_state.get("current_playlist")
    rows = playlists.get(current or "", [])
    if not rows:
        return None, 0, 0

    sp = ensure_user_spotify()
    me = sp.current_user()
    user_id = me["id"]

    target = None
    results = sp.current_user_playlists(limit=50)
    while True:
        for p in results["items"]:
            if p["name"] == playlist_name:
                target = p
                break
        if target or not results.get("next"):
            break
        results = sp.next(results)

    if not target:
        target = sp.user_playlist_create(user=user_id, name=playlist_name, public=public, description=description)

    playlist_id = target["id"]

    uris = []
    misses = 0
    for r in rows:
        uri = r.get("TrackURI") or (("spotify:track:" + str(r["TrackID"])) if r.get("TrackID") else None)
        if not uri:
            title = str(r.get("Title", "")).strip()
            artist = str(r.get("Artists") or r.get("Artist") or "").strip()
            if title:
                q = f'track:"{title}" artist:"{artist}"' if artist else f'track:"{title}"'
                try:
                    sr = sp.search(q=q, type="track", limit=1)
                    items = sr.get("tracks", {}).get("items", [])
                    if items:
                        uri = items[0]["uri"]
                except Exception:
                    pass
        if uri:
            uris.append(uri)
        else:
            misses += 1

    added = 0
    for i in range(0, len(uris), 100):
        chunk = uris[i:i+100]
        sp.user_playlist_add_tracks(user=user_id, playlist_id=playlist_id, tracks=chunk)
        added += len(chunk)

    return playlist_id, added, misses
