# .streamlit/secrets.toml (local example - do not commit real secrets)
SPOTIFY_CLIENT_ID = "YOUR_CLIENT_ID"
SPOTIFY_CLIENT_SECRET = "YOUR_CLIENT_SECRET"
DISCOGS_USER_AGENT = "RepositórioRock/1.0 +https://cfmessias.pt"
DISCOGS_TOKEN = "YOUR_DISCOGS_TOKEN"
